version: '3'

services:
  codebase-knowledge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    restart: unless-stopped